name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          # match local Node.js (where build was verified)
          node-version: '22'
      - name: Debug: Node and npm versions
        run: |
          node -v
          npm -v
          npm --version
      - name: Install dependencies
        # use legacy-peer-deps to reduce CI failures from peer dependency conflicts
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
